config/routes.rb
Seshly::Application.routes.draw do
  resources :tags

  resources :spots
  
  root :to => "spots#index"

end

app/models/spot.rb
class Spot < ActiveRecord::Base
  
  has_and_belongs_to_many :tags
  
  validates_numericality_of :longitude
  validates_numericality_of :latitude
  validates_length_of :title, :maximum => 30
  
  def self.getCategories  
    categories = []  
    for spot in self.all
      categories << spot.category
    end
    
    return categories
  end
  
  def self.getAreas  
    areas = []  
    for spot in self.all
      areas << spot.area
    end
    
    return areas
  end
  
  
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  
  has_and_belongs_to_many :spots
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :spots, :dependent => :destroy
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  # GET /spots
  # GET /spots.xml
  def index
    @spots = Spot.all
    @categories = Spot.getCategories
    @areas = Spot.getAreas
    
    if(params[:category])
      if(params[:category].length > 0)
        @spots = Spot.find_all_by_category(params[:category])
        puts "Filtering by category."
      end
    end
    
    if(params[:area])
      if(params[:area].length > 0)   
        @spots = Spot.find_all_by_area(params[:area])
         puts "Filtering by area."
      end
    end
    
    if (params[:category] and params[:area])
      if (params[:category].length > 0 and params[:area].length > 0)
        @spots = Spot.where("category = ? AND area = ?", params[:category], params[:area])
        puts "Filtering by both category and area."
      end
    end


    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @spots }
      format.json  { render :json => @spots }
    end
  end

  # GET /spots/1
  # GET /spots/1.xml
  def show
    @spot = Spot.find(params[:id])
    @tags = @spot.tags

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @spot }
      format.json  { render :json => @spot }
    end
  end

  # GET /spots/new
  # GET /spots/new.xml
  def new
    @spot = Spot.new
    @tags = Tag.all

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @spot }
      format.json  { render :json => @spot }
    end
  end

  # GET /spots/1/edit
  def edit
    @spot = Spot.find(params[:id])
    @tags = Tag.all
  end

  # POST /spots
  # POST /spots.xml
  def create
    @spot = Spot.new(params[:spot])

    respond_to do |format|
      if @spot.save
        format.html { redirect_to(spots_url, :notice => 'Spot was successfully created.') }
        format.xml  { render :xml => @spot, :status => :created, :location => @spot }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @spot.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /spots/1
  # PUT /spots/1.xml
  def update
    @spot = Spot.find(params[:id])
    @tags = @spot.items

    respond_to do |format|
      if @spot.update_attributes(params[:spot])
        format.html { redirect_to(spots_url, :notice => 'Spot was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @spot.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /spots/1
  # DELETE /spots/1.xml
  def destroy
    @spot = Spot.find(params[:id])
    @spot.destroy

    respond_to do |format|
      format.html { redirect_to(spots_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  # GET /tags
  # GET /tags.xml
  def index
    @tags = Tag.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tags }
    end
  end

  # GET /tags/1
  # GET /tags/1.xml
  def show
    @tag = Tag.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @tag }
    end
  end

  # GET /tags/new
  # GET /tags/new.xml
  def new
    @tag = Tag.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @tag }
    end
  end

  # GET /tags/1/edit
  def edit
    @tag = Tag.find(params[:id])
  end

  # POST /tags
  # POST /tags.xml
  def create
    @tag = Tag.new(params[:tag])

    respond_to do |format|
      if @tag.save
        format.html { redirect_to(@tag, :notice => 'Tag was successfully created.') }
        format.xml  { render :xml => @tag, :status => :created, :location => @tag }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @tag.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /tags/1
  # PUT /tags/1.xml
  def update
    @tag = Tag.find(params[:id])

    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        format.html { redirect_to(@tag, :notice => 'Tag was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @tag.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.xml
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to(tags_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/_user_bar.html.erb
<div id="user_nav">  
  <% if user_signed_in? %>  
    Signed in as <%= current_user.email %>. Not you?  
    <%= link_to "Sign out", destroy_user_session_path %>  
  <% else %>  
    <%= link_to "Sign up", new_user_registration_path %> or  
    <%= link_to "Sign in", new_user_session_path %>  
  <% end %>  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	  <title>Seshly</title>
<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
<style type="text/css">
  html { height: 100% }
  body { height: 100%; margin: 0px; padding: 0px }
  #map_canvas { height: 100% }
</style>

  <%= stylesheet_link_tag :all %>
<%= stylesheet_link_tag "spots" %>
 <%= javascript_include_tag "jquery" %>
  <%= javascript_include_tag :defaults %>

<script type="text/javascript"
    src="http://maps.google.com/maps/api/js?sensor=true">
</script>

  <%= csrf_meta_tag %>
</head>
<body>
  

<%= yield %>



</body>
</html>

app/views/spots/_form.html.erb
<%= javascript_include_tag "tags" %>

<%= form_for(@spot) do |f| %>
  <% if @spot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@spot.errors.count, "error") %> prohibited this spot from being saved:</h2>

      <ul>
      <% @spot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :area %><br />
    <%= f.text_field :area %>
  </div>

  <div class="field">
	<%= f.label :tags %><br />
<input id="add-tags">
  </div>

<% for tag in @tags %>
<li><span>X</span> <%= tag.title %></li>
<input id="spot_tags" name="spot[tags]" type="hidden" value="<%= tag.title%>">
<% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/spots/edit.html.erb
<%= javascript_include_tag "new_spot" %>

<div id="map_canvas" style="float:right;width:60%; height:75%"></div>

<h1>Editing spot</h1>

<%= render 'form' %>

<%= link_to 'Show', @spot %> |
<%= link_to 'Back', spots_path %>

app/views/spots/index.html.erb
 <%= javascript_include_tag "list_spots" %>

<div id="listing" style="float:right;">
	
	<h1>Seshly v.0.1a</h1>

	<table>
	  <tr>
	    <th>Title</th>
	    <th></th>
	    <th></th>
	    <th></th>
	  </tr>

	<% @spots.each do |spot| %>
	  <tr>
	    <td><%= spot.title %></td>
	    <td><%= link_to 'Show', spot %></td>
	    <td><%= link_to 'Edit', edit_spot_path(spot) %></td>
	    <td><%= link_to 'Destroy', spot, :confirm => 'Are you sure?', :method => :delete %></td>
	  </tr>
	<% end %>
	</table>

	<br />
	<form action="/spots/?" method="get">
		<select name="category">
			<option value="">All categories</option>
		<% for category in @categories %>
			<option value="<%= category %>"><%= category%></option>
		<% end %>
		</select>
		<select name="area">
			<option value="">All areas</option>
		<% for area in @areas %>
			<option value="<%= area %>"><%= area %></option>
		<% end %>
		</select>
		<input type="submit" value="Filter">

	</form>

	<%= link_to 'New Spot', new_spot_path %>

</div>

<div id="map_canvas" style="max-width:100%; height:100%"></div>

app/views/spots/new.html.erb
<%= javascript_include_tag "new_spot" %>

<div id="map_canvas" style="float:right;width:60%; height:75%"></div>

<h1>New spot</h1>

<p>Protip: Drag the marker on the map to determine the location of the spot</p>

<%= render 'form' %>

<%= link_to 'Back', spots_path %>

app/views/spots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @spot.title %>
</p>

<p>
  <b>Latitude:</b>
  <%= @spot.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @spot.longitude %>
</p>

<p>
  <b>Address:</b>
  <%= @spot.address %>
</p>

<p>
  <b>Description:</b>
  <%= @spot.description %>
</p>

<p>
  <b>Area:</b>
  <%= @spot.area %>
</p>


<%= link_to 'Edit', edit_spot_path(@spot) %> |
<%= link_to 'Back', spots_path %>

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<h1>Listing tags</h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tags.each do |tag| %>
  <tr>
    <td><%= tag.title %></td>
    <td><%= link_to 'Show', tag %></td>
    <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
    <td><%= link_to 'Destroy', tag, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @tag.title %>
</p>


<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>